
    module.exports = {
  "modulePaths": [
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-gesture-handler",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-reanimated",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-vector-icons",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-safe-area-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-tab-view",
    "/home/divyang/renative_projects/demo_play/node_modules/renative",
    "/home/divyang/renative_projects/demo_play/platformAssets",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-screens",
    "/home/divyang/renative_projects/demo_play/node_modules/react-navigation-tabs",
    "/home/divyang/renative_projects/demo_play/node_modules/react-navigation-stack",
    "/home/divyang/renative_projects/demo_play/node_modules/react-navigation",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-gesture-handler",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-reanimated",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-camera",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-actionsheet",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-root-toast",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-root-siblings",
    "/home/divyang/renative_projects/demo_play/node_modules/static-container",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-material-dropdown",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-material-buttons",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-material-textfield",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-material-ripple",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-easy-grid",
    "/home/divyang/renative_projects/demo_play/node_modules/native-base-shoutem-theme",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-drawer",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-safe-area-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-vector-icons",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-keyboard-aware-scroll-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-tab-view",
    "/home/divyang/renative_projects/demo_play/node_modules/query-string",
    "/home/divyang/renative_projects/demo_play/node_modules/split-on-first",
    "/home/divyang/renative_projects/demo_play/node_modules/strict-uri-encode",
    "/home/divyang/renative_projects/demo_play/node_modules/@react-navigation/core",
    "/home/divyang/renative_projects/demo_play/node_modules/@react-navigation/web",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-animatable",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-collapse-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-color-picker",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-ios-picker",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-modal-datetime-picker",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-modal",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-paper",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-animatable",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-collapse-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-color-picker",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-ios-picker",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-modal-datetime-picker/",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-modal",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-paper",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-platform-touchable",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-safe-area-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-super-grid",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-tab-view",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-vector-icons",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-simple-markdown",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-swipe-gestures",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-switch",
    "/home/divyang/renative_projects/demo_play/node_modules/react-native-orientation-locker",
    "/home/divyang/renative_projects/demo_play/node_modules/react-navigation",
    "/home/divyang/renative_projects/demo_play/node_modules/@react-navigation/native",
    "/home/divyang/renative_projects/demo_play/node_modules/rnv-platform-info",
    "/home/divyang/renative_projects/demo_play/index.webos.js",
    "/home/divyang/renative_projects/demo_play/index.tizen.js",
    "/home/divyang/renative_projects/demo_play/src",
    "/home/divyang/renative_projects/demo_play/packages"
  ],
  "moduleAliases": {
    "react-native": "react-native-web",
    "react-native/Libraries/Renderer/shims/ReactNativePropRegistry": "react-native-web/dist/modules/ReactNativePropRegistry",
    "react-native-gesture-handler": "/home/divyang/renative_projects/demo_play/node_modules/react-native-gesture-handler",
    "react-native-reanimated": "/home/divyang/renative_projects/demo_play/node_modules/react-native-reanimated/web/Animated.js",
    "react-native-vector-icons": "/home/divyang/renative_projects/demo_play/node_modules/react-native-vector-icons",
    "renative": "/home/divyang/renative_projects/demo_play/node_modules/renative"
  },
  "entryFile": "index.web",
  "title": "demo play",
  "assetVersion": "",
  "buildFolder": "server",
  "extensions": [
    "engine-rn-web.jsx",
    "engine-rn-web.js",
    "engine-rn-web.tsx",
    "engine-rn-web.ts",
    "browser.jsx",
    "browser.js",
    "browser.tsx",
    "browser.ts",
    "next.jsx",
    "next.js",
    "next.tsx",
    "next.ts",
    "web.jsx",
    "web.js",
    "web.tsx",
    "web.ts",
    "mjs",
    "jsx",
    "js",
    "json",
    "wasm",
    "tsx",
    "ts"
  ],
  "devServerHost": "0.0.0.0",
  "baseUrl": ""
}